### ISSUE TITLE
What is the current idea about closures in design?

### ISSUE THREAD

**Issue by anqur** [AndrasKovacs/staged#1]
Hi, Andras! I'm recently reading your notes, code and screencasts of this project, I'm really curious about your current idea of closures, since it's not that cohesive from the notes in the codebase. I have some following questions:

* You mentioned that closures could be eliminated. It's gone in both levels? Or just in the object level 0? Or you would be using other things like C structs and function/value pointers as a simplistic form of it?
* Is the idea of closure elimination related to arity analysis? But I think maybe the example of the case-commute is a bit special (not that general)...?

**Comment by AndrasKovacs** [comment]
In the system that is partly implemented now, closures can be fully eliminated from staging output. In the implementation of staging and elaboration itself, closures are still used. Compile-time code is arbitrarily higher-order. 

The C/V-based closure elimination makes arity analysis unnecessary, I'd say that's the relation between them. Arity analysis tries to determine the number of arguments a certain function is called with. With C/V typing, we know all call arities just by looking at the types of functions. What might be a bit confusing, is that it's possible to write under-saturated applications in the surface language. In the output code though only saturated applications are permitted, so we have to eta-expand everything to full arity. I haven't proven that this is possible, but I find it very plausible. Case-commutation seems to be necessary to make expansion to full arity possible.

So far this is about the first-order function type, which should always compile to statically known saturated calls. But I also plan to add an explicitly closure-based function type, looking like `Fun : U0 V -> U0 V -> U0 V`. It takes a value, returns a value, and is itself a value type. The representation would be a "fat pointer", where the first word is a pointer to the code, and the second is a pointer to the struct of captured values. I figured that this representation would have minimal calling overhead in the cases where we don't capture anything. The arity `Fun` is also fully statically known, so we don't have the usual GHC/ML/Lisp overhead of generic calls, but in turn we have to manually pick arities, for example as `Fun (a, b, c) d` for a function with three args.

For `Fun` (or whatever it's called), naturally we could reuse all the known analyses and optimizations that are already known and standard in functional languages.

**Comment by anqur** [comment]
Thanks for your response!

BTW, I also notice that non-generic ADT is only allowed in level 0, with case expressions for term elimination. So I believe something like reuse analysis from the Perceus paper, could be used to achieve the FBIP paradigm, making in-place mutation?

**Comment by AndrasKovacs** [comment]
Perceus is orthogonal to all things I've implemented or considered so far. General considerations apply. Immutable, strict, single-threaded is ideal for reference counting, and the more these are relaxed, the more complications we get.

**Comment by anqur** [comment]
> Immutable, strict, single-threaded is ideal for reference counting, and the more these are relaxed, the more complications we get.

What about copying GC with the reuse analysis for in-place mutation? But I think this would be subtle to the optimization, unlike the tail-call one.

**Comment by AndrasKovacs** [comment]
I don't really get what you mean. In-place mutation requires uniqueness. With copying GC and no other static information, uniqueness can be only approximately learned through whole-program control flow analysis.

Btw, I don't like implicit in-place update. I would rather have typed unique mutable references as in Rust/Clean, and predictable runtime cost. 

I'm generally skeptical about Perceus too. It has a lot more mutator overhead compared to precise GC. There are a bunch of benchmarks in the paper showing big lead over GC, but I'm fairly confident the lead disappears if we increase arena sizes. Probably I should just benchmark it myself. Preliminarily, what I expect is that Perceus could be better than GC in memory- or latency-constrained settings. But in those cases there's a good chance we're better off with regions and lifetimes instead of refcounting.

**Comment by anqur** [comment]
> Btw, I don't like implicit in-place update. I would rather have typed unique mutable references as in Rust/Clean, and predictable runtime cost.

Yes! I totally agree with you about this idea just like OCaml's `ref`, but I thought I was talking about another thing and it is a bit confusing. The *in-place mutation* here is something like this:

```sml
case tree of
(* The matched constructor and the return one are the same,
   so an in-place mutation for `tree` is feasible, eliminating a malloc *)
| Node (left, right) => Node (right, left)
| ...
end
```

And in the *reuse analysis* section (2.5 Reuse Specialization) from the Perceus paper, there is a technique based on the *reuse tokens*:

![perceus-reuse](https://user-images.githubusercontent.com/9910794/126130567-8b612163-0937-4a4f-8389-c28aedb0e426.png)

So I think that a copying GC and this analysis are compatible although it looks kinda subtle, we could make some experiments here.

**Comment by AndrasKovacs** [comment]
That's still about in-place updates. It seems to be about partially updating objects. So it still need uniqueness info, static or dynamic. It's impossible with just copying GC and no static info.

**Comment by anqur** [comment]
> So it still need uniqueness info, static or dynamic.

Phew! I test this in the stable release of Koka (2.1.9), the (runtime) uniqueness check is inserted around the reuse token:

```sml
// collections/foo.kk
public module collections/foo

type mylist<a> {
    C( head : a, tail : mylist<a> )
    N
}

fun map( xs : mylist<a>, f : a -> e b ) : e mylist<b> {
    match(xs) {
        C(x,xx) -> C(f(x), map(xx,f))
        N -> N
    }
}
```

The generated C code:

```c
kk_collections_foo__mylist kk_collections_foo__ctail_map(kk_collections_foo__mylist xs, kk_function_t f1, kk_std_core_types__ctail _acc0, kk_context_t* _ctx) { /* forall<a,b,e> (xs : mylist<a>, f : (a) -> e b, ctail<mylist<b>>) -> e mylist<b> */ 
  kk__tailcall: ;
  if (kk_collections_foo__is_C(xs)) {
    struct kk_collections_foo_C* _con344 = kk_collections_foo__as_C(xs);
    kk_box_t x = _con344->head;
    kk_collections_foo__mylist xx1 = _con344->tail;
    kk_reuse_t _ru_333 = kk_reuse_null; /*reuse*/;
    // XXX: Runtime uniqueness check for the reuse token of `xs`.
    if (kk_collections_foo__mylist_is_unique(xs)) {
      _ru_333 = (kk_collections_foo__mylist_reuse(xs));
    }
    else {
      // XXX: Not reusable.
      kk_box_dup(x);
      kk_collections_foo__mylist_dup(xx1);
      kk_collections_foo__mylist_decref(xs, _ctx);
      _ru_333 = kk_reuse_null;
    }
    kk_box_t x0_268;
    kk_function_t _x345 = kk_function_dup(f1); /*(189) -> 191 190*/
    x0_268 = kk_function_call(kk_box_t, (kk_function_t, kk_box_t, kk_context_t*), _x345, (_x345, x, _ctx)); /*190*/
    if (kk_yielding(kk_context())) {
      kk_reuse_drop(_ru_333, _ctx);
      kk_box_drop(x0_268, _ctx);
      kk_box_t _x346 = kk_std_core_hnd_yield_extend(kk_collections_foo__new_ctail_map_fun347(f1, xx1, _acc0, _ctx), _ctx); /*2*/
      return kk_collections_foo__mylist_unbox(_x346, _ctx);
    }
    kk_collections_foo__mylist _ctail_2490 = kk_collections_foo__mylist_hole(); /*collections/foo/mylist<190>*/;
    // XXX: Create the new `C`. Reuse happens here if possible.
    kk_collections_foo__mylist _ctail_2500 = kk_collections_foo__new_C(_ru_333, x0_268, _ctail_2490, _ctx); /*collections/foo/mylist<190>*/;
// ...
```

In the Koka runtime, the reuse-aided alloc function is:

```c
// kklib.h
static inline kk_block_t* kk_block_alloc_at(kk_reuse_t at, kk_ssize_t size, kk_ssize_t scan_fsize, kk_tag_t tag, kk_context_t* ctx) {
  kk_assert_internal(scan_fsize >= 0 && scan_fsize < KK_SCAN_FSIZE_MAX);
  kk_block_t* b;
  if (at==kk_reuse_null) {
    b = (kk_block_t*)kk_malloc_small(size, ctx);
  }
  else {
    kk_assert_internal(kk_block_is_unique(at)); // TODO: check usable size of `at`
    b = at; // XXX: Got the reuse token, in-place update
  }
  kk_block_init(b, size, scan_fsize, tag);
  return b;
}
```

Thank you for your sincere and insightful responses along the way here! It's really cool to check out so many details about this topic in functional programming!
